from . import all_in_one
from . import pharmacy_prescription_report_wizard
from . import doctor_wise_report
from . import sales_gst_wise_report
from . import hsn_report_wizard
from . import bill_report_wizard
from . import report_ip_billing
from . import report_discharge_billing
from . import lab_collection_report
from . import ot_collection_report
from . import xray_collection_report
from . import casuality_collection_report
from . import audiology_collection_report
from . import op_collection_report
from . import pharmacy_unsettled_bill
from . import lab_unsettle_bill
from . import general_unsettled_bill
from . import casuality_unsettled_bill
from . import audiology_unsettled_bill
from . import xray_unsettled_bill
from . import ot_unsettled_bill
from . import ot_settled_bill
from . import pharmacy_settled_bill
from . import lab_settled_bill
from . import general_settled_bill
from . import casualty_settled_bill
from . import xray_settled_bill
from . import audiology_settled_bill
from . import total_collection_report
from . import cancelled_bill
from . import medicine_reorder
from . import IP_Billing_report
from . import patient_count_report
from . import revenue_report_wizard