# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Homeo_Doctor1',
    'version': '1.0',
    'category': 'Sales/Sales',
    'summary': 'Hospital Management Software',

    'depends': [
        'product', 'hr', 'account', 'purchase', 'web'],
    'data': [
        "views/patient_reg.xml",
        "views/menu.xml",
        "views/medicine_entry.xml",
        "views/patient.xml",
        "views/doctor_profile_views.xml",
        "views/doctor_lab_report_views.xml",
        "views/product_product_inherit.xml",
        "views/pharmacy.xml",
        "views/admitted_patient_details.xml",
        "views/ot_management.xml",
        "views/patient_insurance.xml",
        "views/patient_appointments.xml",
        "views/doctor_department.xml",
        # "views/hr_module_custom.xml",
        "report/patient_report.xml",
        "report/transfer_print.xml",
        "report/patient_registion_report.xml",
        "report/admitted_patient_report.xml",
        "report/consultation_report.xml",
        "views/patient.xml",
        "views/ct_scan.xml",
        "views/mri_scan.xml",
        "views/x_ray_scan.xml",
        "views/patient_appointments.xml",
        "views/audiology.xml",
        "views/templates.xml",
        "report/ct_invoice_template.xml",
        "report/ct_reports.xml",
        "report/mri_invoice_template.xml",
        "report/mri_reports.xml",
        "report/x_ray_invoice_template.xml",
        "report/x_ray_reports.xml",
        "report/audiology_invoice_template.xml",
        "report/audiology_reports.xml",
        "report/lab_report.xml",
        "report/lab_report.xml",
        "report/Lab_report_report.xml",
        "report/report_patient_card.xml",
        "report/report_action.xml",
        "report/patient_challan_report.xml",
        "report/intent_report.xml",
        "report/lab_result_report.xml",
        "report/general_billing_report.xml",
        "report/view_patient_registration_report_wizard.xml",
        "report/general_billing_wizard_report.xml",
        "report/lab_report.xml",
        "report/lab_billing_wizard_report.xml",
        "report/pharmacy_description_report.xml",
        "report/supplier_billing_report.xml",
        "report/admitted_patient_billing_wizard.xml",
        "report/appointment_challan.xml",
        "report/admission_challan_report.xml",
        "report/admission_discharge_challan.xml",
        "report/ip_part_challan.xml",
        "report/all_in_one_report.xml",
        "report/combined_report_template.xml",
        "report/pharmacy_report_template.xml",
        "report/fast_moving_medicine_report.xml",
        "report/doctor_wise_report.xml",
        "report/slaes_gst_wise_report.xml",
        "report/sales_gst_wise_report_wizard.xml",
        "report/hsn_report_wizard_view.xml",
        "report/report_hsn_wise.xml",
        "report/bill_report_wizard.xml",
        "report/ip_biling_report.xml",
        "report/ot_bill_report.xml",
        "report/x_ray_bill_report.xml",
        "report/audiology_bill_report.xml",
        "report/casuality_bill_report.xml",
        "report/dead_stock_report.xml",
        "report/slow_moving_medicine_list.xml",
        "report/Lab_collection_report.xml",
        "report/ot_collection_report.xml",
        "report/xray_collection_reports.xml",
        "report/casuality_collection_report.xml",
        "report/audiology_collection_report.xml",
        "report/op_collection_report.xml",
        "report/pharmacy_unsettled_bill.xml",
        "report/lab_unsettled_bill.xml",
        "report/general_unsettled_bill.xml",
        "report/casualty_unsetteld_bill.xml",
        "report/audiology_unsetteld_bill.xml",
        "report/xray_unsettled_bill.xml",
        "report/ot_unsettled_bill.xml",
        "report/ot_settled_bill.xml",
        "report/casualty_settled_bill.xml",
        "report/bill_type_wizard_view.xml",
        "report/ot_settled_bill.xml",
        "report/pharmacy_settled_bill.xml",
        "report/lab_settled_bill.xml",
        "report/general_settled_bill.xml",
        "report/xray_settled_bill.xml",
        "report/audiology_settled_bill.xml",
        "report/bill_type_settled.xml",
        "report/consolidated_discharge_bill.xml",
        "report/total_collection_report.xml",
        "report/cancelled_bill.xml",
        "report/medicine_reorder.xml",
        "report/ipdischarge_billing_report.xml",
        "report/patient_count_report.xml",
        "views/custom_title.xml",
        "views/account_move_view.xml",
        "views/register_paymeny.xml",
        "views/intent.xml",
        "views/casualty.xml",
        "views/stock_entry_view.xml",
        "views/appontment_payment_wizard.xml",
        "views/master.xml",
        "views/purchase_order_views.xml",
        "views/op_category.xml",
        "views/lab_payment_wizard.xml",
        "views/lab_resultant_confi.xml",
        "views/general_department.xml",
        "views/general_dept_costing.xml",
        "views/general_billing.xml",
        "views/general_billing.xml",
        "views/lab_result_page.xml",
        "views/room_config.xml",
        "views/hospital_block.xml",
        "views/hospital_room_type.xml",
        "views/admitted_patient_history.xml",
        "views/sale_return_form.xml",
        "views/stock_transfer.xml",
        "views/bill_status_wizard_view.xml",
        "views/ip_return_medicine.xml",
        "views/hr_employee_kanban_inherit.xml",
        "views/ip_part_billing.xml",
        "views/hr_employee.xml",
        "views/pharmacy_prescription_report_wizard.xml",
        "views/res_partner_inherit.xml",
        "views/dashboard_model_kanban.xml",
        "views/fast_moving_medicines.xml",
        "views/doctor_billing_report_wizard_view.xml",
        "views/x_ray_test_view.xml",
        "views/ot_test_view.xml",
        "views/audiology_test_view.xml",
        "views/casuality_billing.xml",
        "views/audiology_billing.xml",
        "views/xray_billing.xml",
        "views/ot_billing.xml",
        "views/manage_insurance_view.xml",
        "views/patient_wallet.xml",
        "views/login_template.xml",
        "views/discharge_bill.xml",
        "views/menu_vendor_inherit.xml",
        "views/medicine_category_views.xml",
        "views/doctor_list_menu.xml",
        "views/doctor_list_two.xml",
        "views/zero_stock_report_view.xml",
        "data/ir_sequence_data.xml",
        'security/groups.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'homeo_doctor/static/src/js/custom_filter.js',
            'homeo_doctor/static/src/js/blank_value.js',
            'homeo_doctor/static/src/css/styles.css',
            'homeo_doctor/static/src/js/expiry_dashboard_popup.js',
        ],
    },
    'demo': [

    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
